spring:
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    open-in-view: true
    hibernate:
      ddl-auto: none
  #      ddl-auto: create-drop
  #      ddl-auto: validate

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: "jdbc:oracle:thin:@//83.228.124.173:6223/iveta_vasileva"
    username: "iveta_vasileva"
    password: "dbpass"
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE